version: '3.8'
services:
  app:
    build: .
    container_name: investments-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/investments-api
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres@123

  db:
    image: postgres:17-alpine
    container_name: db-investments-api
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: investments-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123